### ISSUE TITLE
SQLSTATE[22003]: Numeric value out of range

### ISSUE THREAD

**Issue by miller-itsec** [Avira/virex#2]
Running `php /var/www/protected/commands/console.php archives process` produces the error:

`processing /var/www/incoming/detected/daily/2018-01-12-0746-650.zip[CRITICAL ERROR:CDbCommand failed to execute the SQL statement: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'files_size_psf' at row 1]`

The file:

```
ls -al /var/www/incoming/detected/daily/2018-01-12-0746-650.zip
-rw-rw-r-- 1 user group 151103374 Jan 12 14:47 /var/www/incoming/detected/daily/2018-01-12-0746-650.zip
```

Side note: trying to re-run produces

`[ERROR] /var/www/incoming locked!`

**Comment by miller-itsec** [comment]
Changing the files_size_psf to bigint(10) seems to fix the issue:

![image](https://user-images.githubusercontent.com/20181242/34911180-0ef572c8-f8c5-11e7-969d-3fe92d0c455f.png)

**Comment by razvanmoiseavira** [comment]
Hello,

Thank you for your report! We just fixed this issue.

All the best regards,
Razvan Moise
