### ISSUE TITLE
Problem with sampleshare.php

### ISSUE THREAD

**Issue by guillermomolla** [Avira/virex#3]
I followed the guide but when I execute the php i recieve:
Requesting metadata.. Server returned ERROR! => Error encrypting buffer!

Any help please?

**Comment by razvanmoiseavira** [comment]
Hello. Unfortunately the PHP does not support PHP7 for the moment. 
We will make an update soon.
Thanks for reporting

**Comment by guillermomolla** [comment]
I'm using php5 and I'm getting the same error

**Comment by guillermomolla** [comment]
As there is no answer i decide to close the ticket
